package com.main.pubmanagement.constant;

public interface AppConstant {
    String DATA_BASE_NAME = "pubmanagere.db";
    String DOT = "[.,]";
    String TABLE_USER = "USER";
    String COLUMN_USER_ID = "IDUSER";
    String COLUMN_USER_NAME = "NAMEUSER";
    String COLUMN_USER_USERNAME = "USERNAMEUSER";
    String COLUMN_USER_PASSWORD = "PASSWORDUSER";
    String COLUMN_USER_ROLE = "ROLEDUSER";
    String COLUMN_USER_SHIFT = "SHIFTDUSER";

    String TABLE_STOREY = "STOREY";
    String COLUMN_STOREY_ID = "IDSTOREY";
    String COLUMN_STOREY_NAME = "NAMESTOREY";

    String TABLE_TABLE_RESTAURANT = "TABLE_RESTAURANT";
    String COLUMN_RESTAURANT_ID = "IDRESTAURANT";
    String COLUMN_RESTAURANT_NAME = "NAMERESTAURANT";
    String COLUMN_RESTAURANT_COUNT_CHAIR = "COUNTCHAIRRESTAURANT";
    String COLUMN_RESTAURANT_STATUS = "STATUSRESTAURANT";

    String TABLE_MENU_TYPE = "MENUTYPE";
    String COLUMN_MENU_TYPE_ID = "IDMENUTYPE";
    String COLUMN_MENU_TYPE_NAME = "NAMEMENUTYPE";


    String TABLE_MENU = "MENU";
    String COLUMN_MENU_ID = "IDMENU";
    String COLUMN_MENU_NAME = "NAMEMENU";
    String COLUMN_MENU_PRICE = "PRICEMENU";
    String COLUMN_MENU_UNIT = "UNITMENU";
    String COLUMN_MENU_DISCOUNT = "DISCOUNT";
    String COLUMN_MENU_CONTENT = "MENUCONTENT";
    String COLUMN_MENU_COUNT = "MENUCOUNT";

    String TABLE_ORDER = "TABLEORDER";
    String COLUMN_ORDER_ID = "IDORDER";
    String COLUMN_ORDER_STATUS = "STATUSORDER";
    String COLUMN_ORDER_CREATE_AT = "CREATEATORDER";
    String COLUMN_ORDER_TOTAL_PRICE = "TOTALPRICEORDER";
    String COLUMN_ORDER_PERSON = "PERSONPRICEORDER";
    String TABLE_ORDER_DETAIL = "TABLEORDERDETAIL";
    String COLUMN_ORDER_DETAIL_ID = "IDORDERDETAIL";
    String COLUMN_ORDER_DETAIL_QUANTITY = "QUANTITYORDERDETAIL";
    String COLUMN_ORDER_DETAIL_DISCOUNT = "DISCOUNTORDERDETAIL";
    String COLUMN_ORDER_DETAIL_PRICE = "PRICEORDERDETAIL";
    String COLUMN_ORDER_DETAIL_NAME = "NAMEORDERDETAIL";
    String COLUMN_ORDER_DETAIL_ID_MENU = "NAMEORDERDETAILIDMENU";

    String TABLE_BILL = "TABLEBILL";

    String COLUMN_BILL_ID = "IDBILL";
    String COLUMN_BILL_TYPE = "TYPEBILL";
    String COLUMN_BILL_PRICE = "PRICEBILL";
    String COLUMN_BILL_PRICE_DISCOUNT = "PRICEDISCOUNTBILL";
    String COLUMN_BILL_TIME = "TIMEBILL";
    String COLUMN_BILL_COUNT_PERSON = "COUNTPERSONBILL";

    String TABLE_BILL_INFO = "TABLEBILLINFO";
    String COLUMN_BILL_INFO_ID = "IDBILLINFO";
    String COLUMN_BILL_INFO_QUANTITY = "QUANTITYBILLINFO";
    String COLUMN_BILL_INFO_DISCOUNT = "DISCOUNTBILLINFO";

}
