package com.main.pubmanagement.constant;

public interface AppConstant {
    String DATA_BASE_NAME = "pubmanagere.db";
    String TABLE_USER = "USER";
    String COLUMN_USER_ID = "IDUSER";
    String COLUMN_USER_NAME = "NAMEUSER";
    String COLUMN_USER_USERNAME = "USERNAMEUSER";
    String COLUMN_USER_PASSWORD = "PASSWORDUSER";
    String COLUMN_USER_ROLE = "ROLEDUSER";
    String COLUMN_USER_SHIFT = "SHIFTDUSER";

    String TABLE_STOREY = "STOREY";
    String COLUMN_STOREY_ID = "IDSTOREY";
    String COLUMN_STOREY_NAME = "NAMESTOREY";

    String TABLE_TABLE_RESTAURANT = "TABLE_RESTAURANT";
    String COLUMN_RESTAURANT_ID = "IDRESTAURANT";
    String COLUMN_RESTAURANT_NAME = "NAMERESTAURANT";
    String COLUMN_RESTAURANT_COUNT_CHAIR = "COUNTCHAIRRESTAURANT";
    String COLUMN_RESTAURANT_STATUS = "STATUSRESTAURANT";

    String TABLE_MENU_TYPE = "MENUTYPE";
    String COLUMN_MENU_TYPE_ID = "IDMENUTYPE";
    String COLUMN_MENU_TYPE_NAME = "NAMEMENUTYPE";


    String TABLE_MENU = "MENU";
    String COLUMN_MENU_ID = "IDMENU";
    String COLUMN_MENU_NAME = "NAMEMENU";
    String COLUMN_MENU_PRICE = "PRICEMENU";
    String COLUMN_MENU_UNIT = "UNITMENU";
    String COLUMN_MENU_DISCOUNT = "DISCOUNT";
}
